### ISSUE TITLE
Have you already considered adding a software license?

### ISSUE THREAD

**Issue by Borginator** [ouven/akka-visualmailbox#3]
Hi, I'd like to have a play with this project locally to see if I can get some pictures of my system, but I didn't want to do that if it was against your intended permission.

https://help.github.com/articles/licensing-a-repository/

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Thanks!

**Comment by ouven** [comment]
#4
