### ISSUE TITLE
Rendering w/o mailbox numbers and super slow in Chrome

### ISSUE THREAD

**Issue by myfear** [ouven/akka-visualmailbox#5]
Hi,

I've been playing around with latest snapshop and my renderings are looking weird plus there are no mailbox numbers show. Safari is barely able to render the page at all. Chrome Version 73.0.3683.86 can do it but is slow and doesn't seem to scale to the whole system. Example screenshot below.
Any idea where I should look to solve this?

![download](https://user-images.githubusercontent.com/1358554/55136819-b1371280-512f-11e9-9c3c-060239bfe3e5.png)

Thanks for this nice project though. Fun to play with!
M

**Comment by myfear** [comment]
I think I found it. I was running my sample project with Java 8. Works like a charm with Java >=10.

**Comment by ouven** [comment]
Sorry, for ignoring this. I haven't seen it. I have to figure out, why GitHub doesn't notify me by mail on new issues/comments and so on ☹️
